sudo: false
language: go
go: 1.5

install:
  - go get -v -t ./...

before_script:
  - ./ci/create-postgres-tables.sh

script:
  - go test ./...

after_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
